### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Eviu** [Luscarvalho/grupo-dos-cinefilos#1]
![image](https://github.com/Luscarvalho/grupo-dos-cinefilos/assets/7392315/24d85981-a3c7-4aaf-867d-db44df5c8929)

**Comment by Astralzao** [comment]
poderia por favor atualizar o site para uma versão responsiva?

**Comment by Luscarvalho** [comment]
Será resolvido em breve!

**Comment by Luscarvalho** [comment]
Já foi resolvido
